name: Update Flake Lock

on:
  workflow_dispatch:  # Manual triggers
  push:
    branches: [main]  # Runs on every push to main

jobs:
  update-and-verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git diff
          token: ${{ secrets.GITHUB_TOKEN }}  # Needed for push

      - name: Install Nix with flakes
        uses: DeterminateSystems/nix-installer-action@v3

      - name: Update flake inputs
        run: nix flake update

      - name: Verify flake builds
        run: nix flake check

      - name: Commit and push changes
        if: success()  # Only run if previous steps succeeded
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add flake.lock
          # Only commit if lock file changed
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update flake.lock" && git push)

