name: Update Flake Lock

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update-and-verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/graalvm
          sudo rm -rf /usr/local/julia*

      - name: Install Nix with flakes
        uses: DeterminateSystems/nix-installer-action@v3

      - name: Update flake inputs
        run: nix flake update

      - name: Verify flake builds
        run: nix flake check

      - name: Commit and push changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add flake.lock
          git diff --quiet || (git commit -m "Update flake.lock" && git push)
